# This Python file uses the following encoding: utf-8
# ISO 3166-1 country codes. 
# Country Names based on http://opencountrycodes.appspot.com/python

from tower import ugettext_lazy as _lazy

countries = {'AF': _lazy(u'Afghanistan'),
			 'AX': _lazy(u'Aland Islands'),
			 'AL': _lazy(u'Albania'),
			 'DZ': _lazy(u'Algeria'),
			 'AS': _lazy(u'American Samoa'),
			 'AD': _lazy(u'Andorra'),
			 'AO': _lazy(u'Angola'),
			 'AI': _lazy(u'Anguilla'),
			 'AQ': _lazy(u'Antarctica'),
			 'AG': _lazy(u'Antigua and Barbuda'),
			 'AR': _lazy(u'Argentina'),
			 'AM': _lazy(u'Armenia'),
			 'AW': _lazy(u'Aruba'),
			 'AU': _lazy(u'Australia'),
			 'AT': _lazy(u'Austria'),
			 'AZ': _lazy(u'Azerbaijan'),
			 'BS': _lazy(u'Bahamas'),
			 'BH': _lazy(u'Bahrain'),
			 'BD': _lazy(u'Bangladesh'),
			 'BB': _lazy(u'Barbados'),
			 'BY': _lazy(u'Belarus'),
			 'BE': _lazy(u'Belgium'),
			 'BZ': _lazy(u'Belize'),
			 'BJ': _lazy(u'Benin'),
			 'BM': _lazy(u'Bermuda'),
			 'BT': _lazy(u'Bhutan'),
			 'BO': _lazy(u'Bolivia'),
			 'BQ': _lazy(u'Bonaire'),
			 'BA': _lazy(u'Bosnia and Herzegovina'),
			 'BW': _lazy(u'Botswana'),
			 'BV': _lazy(u'Bouvet Island'),
			 'BR': _lazy(u'Brazil'),
			 'IO': _lazy(u'British Indian Ocean Territory'),
			 'BN': _lazy(u'Brunei Darussalam'),
			 'BG': _lazy(u'Bulgaria'),
			 'BF': _lazy(u'Burkina Faso'),
			 'BI': _lazy(u'Burundi'),
			 'KH': _lazy(u'Cambodia'),
			 'CM': _lazy(u'Cameroon'),
			 'CA': _lazy(u'Canada'),
			 'CV': _lazy(u'Cape Verde'),
			 'KY': _lazy(u'Cayman Islands'),
			 'CF': _lazy(u'Central African Republic'),
			 'TD': _lazy(u'Chad'),
			 'CL': _lazy(u'Chile'),
			 'CN': _lazy(u'China'),
			 'CX': _lazy(u'Christmas Island'),
			 'CC': _lazy(u'Cocos (Keeling) Islands'),
			 'CO': _lazy(u'Colombia'),
			 'KM': _lazy(u'Comoros'),
			 'CG': _lazy(u'Congo'),
			 'CD': _lazy(u'Congo, The Democratic Republic of the'),
			 'CK': _lazy(u'Cook Islands'),
			 'CR': _lazy(u'Costa Rica'),
			 'CI': _lazy(u"Cote D'ivoire"),
			 'HR': _lazy(u'Croatia'),
			 'CU': _lazy(u'Cuba'),
			 'CW': _lazy(u'Curacao'),
			 'CY': _lazy(u'Cyprus'),
			 'CZ': _lazy(u'Czech Republic'),
			 'DK': _lazy(u'Denmark'),
			 'DJ': _lazy(u'Djibouti'),
			 'DM': _lazy(u'Dominica'),
			 'DO': _lazy(u'Dominican Republic'),
			 'EC': _lazy(u'Ecuador'),
			 'EG': _lazy(u'Egypt'),
			 'SV': _lazy(u'El Salvador'),
			 'GQ': _lazy(u'Equatorial Guinea'),
			 'ER': _lazy(u'Eritrea'),
			 'EE': _lazy(u'Estonia'),
			 'ET': _lazy(u'Ethiopia'),
			 'FK': _lazy(u'Falkland Islands (Malvinas)'),
			 'FO': _lazy(u'Faroe Islands'),
			 'FJ': _lazy(u'Fiji'),
			 'FI': _lazy(u'Finland'),
			 'FR': _lazy(u'France'),
			 'GF': _lazy(u'French Guiana'),
			 'PF': _lazy(u'French Polynesia'),
			 'TF': _lazy(u'French Southern Territories'),
			 'GA': _lazy(u'Gabon'),
			 'GM': _lazy(u'Gambia'),
			 'GE': _lazy(u'Georgia'),
			 'DE': _lazy(u'Germany'),
			 'GH': _lazy(u'Ghana'),
			 'GI': _lazy(u'Gibraltar'),
			 'GR': _lazy(u'Greece'),
			 'GL': _lazy(u'Greenland'),
			 'GD': _lazy(u'Grenada'),
			 'GP': _lazy(u'Guadeloupe'),
			 'GU': _lazy(u'Guam'),
			 'GT': _lazy(u'Guatemala'),
			 'GG': _lazy(u'Guernsey'),
			 'GN': _lazy(u'Guinea'),
			 'GW': _lazy(u'Guinea-Bissau'),
			 'GY': _lazy(u'Guyana'),
			 'HT': _lazy(u'Haiti'),
			 'HM': _lazy(u'Heard Island and McDonald Islands'),
			 'VA': _lazy(u'Vatican City State'),
			 'HN': _lazy(u'Honduras'),
			 'HK': _lazy(u'Hong Kong'),
			 'HU': _lazy(u'Hungary'),
			 'IS': _lazy(u'Iceland'),
			 'IN': _lazy(u'India'),
			 'ID': _lazy(u'Indonesia'),
			 'IR': _lazy(u'Iran'),
			 'IQ': _lazy(u'Iraq'),
			 'IE': _lazy(u'Ireland'),
			 'IM': _lazy(u'Isle of Man'),
			 'IL': _lazy(u'Israel'),
			 'IT': _lazy(u'Italy'),
			 'JM': _lazy(u'Jamaica'),
			 'JP': _lazy(u'Japan'),
			 'JE': _lazy(u'Jersey'),
			 'JO': _lazy(u'Jordan'),
			 'KZ': _lazy(u'Kazakhstan'),
			 'KE': _lazy(u'Kenya'),
			 'KI': _lazy(u'Kiribati'),
			 'KP': _lazy(u"North Korea"),
			 'KR': _lazy(u'South Korea'),
			 'KW': _lazy(u'Kuwait'),
			 'KG': _lazy(u'Kyrgyzstan'),
			 'LA': _lazy(u"Laos"),
			 'LV': _lazy(u'Latvia'),
			 'LB': _lazy(u'Lebanon'),
			 'LS': _lazy(u'Lesotho'),
			 'LR': _lazy(u'Liberia'),
			 'LY': _lazy(u'Libyan Arab Jamahiriya'),
			 'LI': _lazy(u'Liechtenstein'),
			 'LT': _lazy(u'Lithuania'),
			 'LU': _lazy(u'Luxembourg'),
			 'MO': _lazy(u'Macao'),
			 'MK': _lazy(u'Macedonia'),
			 'MG': _lazy(u'Madagascar'),
			 'MW': _lazy(u'Malawi'),
			 'MY': _lazy(u'Malaysia'),
			 'MV': _lazy(u'Maldives'),
			 'ML': _lazy(u'Mali'),
			 'MT': _lazy(u'Malta'),
			 'MH': _lazy(u'Marshall Islands'),
			 'MQ': _lazy(u'Martinique'),
			 'MR': _lazy(u'Mauritania'),
			 'MU': _lazy(u'Mauritius'),
			 'YT': _lazy(u'Mayotte'),
			 'MX': _lazy(u'Mexico'),
			 'FM': _lazy(u'Micronesia'),
			 'MD': _lazy(u'Moldova'),
			 'MC': _lazy(u'Monaco'),
			 'MN': _lazy(u'Mongolia'),
			 'ME': _lazy(u'Montenegro'),
			 'MS': _lazy(u'Montserrat'),
			 'MA': _lazy(u'Morocco'),
			 'MZ': _lazy(u'Mozambique'),
			 'MM': _lazy(u'Myanmar'),
			 'NA': _lazy(u'Namibia'),
			 'NR': _lazy(u'Nauru'),
			 'NP': _lazy(u'Nepal'),
			 'NL': _lazy(u'Netherlands'),
			 'NC': _lazy(u'New Caledonia'),
			 'NZ': _lazy(u'New Zealand'),
			 'NI': _lazy(u'Nicaragua'),
			 'NE': _lazy(u'Niger'),
			 'NG': _lazy(u'Nigeria'),
			 'NU': _lazy(u'Niue'),
			 'NF': _lazy(u'Norfolk Island'),
			 'MP': _lazy(u'Northern Mariana Islands'),
			 'NO': _lazy(u'Norway'),
			 'OM': _lazy(u'Oman'),
			 'PK': _lazy(u'Pakistan'),
			 'PW': _lazy(u'Palau'),
			 'PS': _lazy(u'Palestinian Territory'),
			 'PA': _lazy(u'Panama'),
			 'PG': _lazy(u'Papua New Guinea'),
			 'PY': _lazy(u'Paraguay'),
			 'PE': _lazy(u'Peru'),
			 'PH': _lazy(u'Philippines'),
			 'PN': _lazy(u'Pitcairn'),
			 'PL': _lazy(u'Poland'),
			 'PT': _lazy(u'Portugal'),
			 'PR': _lazy(u'Puerto Rico'),
			 'QA': _lazy(u'Qatar'),
			 'RE': _lazy(u'Reunion'),
			 'RO': _lazy(u'Romania'),
			 'RU': _lazy(u'Russian Federation'),
			 'RW': _lazy(u'Rwanda'),
			 'BL': _lazy(u'Saint Barthelemy'),
			 'SH': _lazy(u'Saint Helena'),
			 'KN': _lazy(u'Saint Kitts and Nevis'),
			 'LC': _lazy(u'Saint Lucia'),
			 'MF': _lazy(u'Saint Martin (French Part)'),
			 'PM': _lazy(u'Saint Pierre and Miquelon'),
			 'VC': _lazy(u'Saint Vincent and the Grenadines'),
			 'WS': _lazy(u'Samoa'),
			 'SM': _lazy(u'San Marino'),
			 'ST': _lazy(u'Sao Tome and Principe'),
			 'SA': _lazy(u'Saudi Arabia'),
			 'SN': _lazy(u'Senegal'),
			 'RS': _lazy(u'Serbia'),
			 'SC': _lazy(u'Seychelles'),
			 'SL': _lazy(u'Sierra Leone'),
			 'SG': _lazy(u'Singapore'),
			 'SX': _lazy(u'Sint Maarten (Dutch Part)'),
			 'SK': _lazy(u'Slovakia'),
			 'SI': _lazy(u'Slovenia'),
			 'SB': _lazy(u'Solomon Islands'),
			 'SO': _lazy(u'Somalia'),
			 'ZA': _lazy(u'South Africa'),
			 'GS': _lazy(u'South Georgia and the South Sandwich Islands'),
			 'ES': _lazy(u'Spain'),
			 'LK': _lazy(u'Sri Lanka'),
			 'SD': _lazy(u'Sudan'),
			 'SR': _lazy(u'Suriname'),
			 'SJ': _lazy(u'Svalbard and Jan Mayen'),
			 'SZ': _lazy(u'Swaziland'),
			 'SE': _lazy(u'Sweden'),
			 'CH': _lazy(u'Switzerland'),
			 'SY': _lazy(u'Syrian Arab Republic'),
			 'TW': _lazy(u'Taiwan'),
			 'TJ': _lazy(u'Tajikistan'),
			 'TZ': _lazy(u'Tanzania'),
			 'TH': _lazy(u'Thailand'),
			 'TL': _lazy(u'Timor-Leste'),
			 'TG': _lazy(u'Togo'),
			 'TK': _lazy(u'Tokelau'),
			 'TO': _lazy(u'Tonga'),
			 'TT': _lazy(u'Trinidad and Tobago'),
			 'TN': _lazy(u'Tunisia'),
			 'TR': _lazy(u'Turkey'),
			 'TM': _lazy(u'Turkmenistan'),
			 'TC': _lazy(u'Turks and Caicos Islands'),
			 'TV': _lazy(u'Tuvalu'),
			 'UG': _lazy(u'Uganda'),
			 'UA': _lazy(u'Ukraine'),
			 'AE': _lazy(u'United Arab Emirates'),
			 'GB': _lazy(u'United Kingdom'),
			 'US': _lazy(u'United States'),
			 'UM': _lazy(u'United States Minor Outlying Islands'),
			 'UY': _lazy(u'Uruguay'),
			 'UZ': _lazy(u'Uzbekistan'),
			 'VU': _lazy(u'Vanuatu'),
			 'VE': _lazy(u'Venezuela'),
			 'VN': _lazy(u'Viet Nam'),
			 'VG': _lazy(u'Virgin Islands, British'),
			 'VI': _lazy(u'Virgin Islands, U.S.'),
			 'WF': _lazy(u'Wallis and Futuna'),
			 'EH': _lazy(u'Western Sahara'),
			 'YE': _lazy(u'Yemen'),
			 'ZM': _lazy(u'Zambia'),
			 'ZW': _lazy(u'Zimbabwe')}
